#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
CREATE ROLE ${HEALTHCHECK_USER} LOGIN PASSWORD '${HEALTHCHECK_PASS}';
CREATE USER ${DB_REP_USER} REPLICATION LOGIN ENCRYPTED PASSWORD '${DB_REP_PASS}';
EOSQL